### ISSUE TITLE
Add Weapons

### ISSUE THREAD

**Issue by mkli90** [mkli90/ptauri#5]
A very basic weapon. For test purposes this model can be used:
http://tf3dm.com/3d-model/ak-47-avtomat-kalashnikova-1947-hires-textures-detailed-mesh-82848.html

To finish this issue one should be able to:
 - [x] Get the weapon out (Animation already there, Weapon Mesh still needed)
 - [x] Shoot ray-traces
 - [x] Reload (Animation already there, Mag meshs still needed)
 - [x] Shoot other players (lower their HP on hit) [cross-reference to #3]

 - [x] Add crosshair and adjust character alignment relative to the camera. (Moved to #9)
 - [x]  0 <= Health <= 100.  (Moved to #26)

This can be done in Blueprints or in C++.
Tutorial (Blueprints): https://www.youtube.com/watch?v=h26Fvk2RWhw&feature=youtu.be&t=3945

**Comment by mkli90** [comment]
In future releases all weapons should be inherited by a "Weapon"-blueprint which delivers some variables:
 - Clip Size
 - Max Ammo Capacity
 - Mesh
 - Damage
